// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs song-v6_types.go

package main

const FWfxm_1 = 0x1
const FWfxm_2 = 0x2
const FWfxm_3 = 0x4
const FWfxm_4 = 0x8
const FWfxm_5 = 0x10
const FWfxm_acoustc = 0x40
const FWfxm_dirty = 0x80

type FWamp_defaults struct {
	Dirty_gain	uint8
	Clean_gain	uint8
	Gate		uint8
}
type FWamp_descriptor struct {
	Midi_cc [5]uint8
}
type FWaxe_midi_program struct {
	Defaults	FWamp_defaults
	Amps		[2]FWamp_descriptor
}

type FWamp struct {
	Gain	uint8
	Gate	uint8
	Fx	uint8
	Volume	uint8
}
type FWscene_descriptor struct {
	Amp [2]FWamp
}
type FWsong struct {
	Name			[20]uint8
	Axe_midi_program	uint8
	Td50_midi_program	uint8
	Tempo			uint8
	Amp_defaults		FWamp_defaults
	Scene_count		uint8
	Scene			[12]FWscene_descriptor
	X_padding		[5]uint8
}
type FWset_entry struct {
	Song uint8
}
type FWset_list struct {
	Count	uint8
	Entries	[125]FWset_entry
}

const FWmax_axe_midi_program_count = 0x9
const FWaxe_midi_padding = 0xb

const FWamp_sizeof = 0x4
const FWsong_sizeof = 0x80
const FWset_entry_sizeof = 0x1
const FWset_list_sizeof = 0x7e

const FWscene_count_max = 0xc

const FWmax_set_length = 0x7d
